name: "🛂 Add an Activity"
description: "Propose a new kid-friendly activity for the map"
labels: ["add-activity"]

body:
  - type: markdown
    attributes:
      value: |
        ### ℹ️ Please fill out this form to add a new activity
        *All fields are required unless marked as optional.*
        
        **Tip:** Check existing activities to maintain consistent formatting.

  # Basic Information
  - type: input
    id: name
    attributes:
      label: "Activity Name"
      description: "The official name of the location or activity"
      placeholder: "Xpark Aquarium (Qingpu)"
    validations:
      required: true

  - type: input
    id: region
    attributes:
      label: "Region/County"
      description: "Taiwan county/region (e.g., Taoyuan, Taipei, Hsinchu, Yilan)"
      placeholder: "Taoyuan"
    validations:
      required: true

  - type: input
    id: city
    attributes:
      label: "City"
      description: "City where the activity is located"
      placeholder: "Taoyuan"
    validations:
      required: true

  - type: input
    id: district
    attributes:
      label: "District/Area"
      description: "District or area within the city"
      placeholder: "Zhongli"
    validations:
      required: true

  - type: dropdown
    id: indoor_outdoor
    attributes:
      label: "Indoor/Outdoor"
      description: "Is this primarily an indoor, outdoor, or mixed activity?"
      options:
        - "Indoor"
        - "Outdoor"
        - "Mixed"
    validations:
      required: true

  # Categories and Tags
  - type: checkboxes
    id: categories
    attributes:
      label: "Categories (select at least one)"
      description: "Main categories that best describe this activity"
      options:
        - label: "Aquarium"
        - label: "Museum"
        - label: "Science"
        - label: "Art"
        - label: "Children"
        - label: "Theme Park"
        - label: "Play"
        - label: "Trail"
        - label: "Park"
        - label: "Zoo"
        - label: "Lake"
        - label: "Waterfront"
        - label: "Old Street"
        - label: "Bike Path"
        - label: "Beach"
        - label: "Waterplay"
        - label: "Farm/Ranch"
        - label: "Animals"
        - label: "Viewpoint"
        - label: "Boat"
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: "Tags (comma separated)"
      description: "Additional descriptive tags (e.g., 'learning, nature, food, AC, stroller')"
      placeholder: "learning, nature, food, AC, stroller"
    validations:
      required: false

  # Description
  - type: textarea
    id: desc
    attributes:
      label: "Description"
      description: "A brief description of the activity (minimum 5 characters)"
      placeholder: |
        What makes this place great for kids? Include any highlights, special features, 
        or tips for families visiting with children.
        
        Example: "Modern aquarium with immersive tanks, penguins, and shows—great A/C learning day."
    validations:
      required: true

  # Cost and Age Information
  - type: input
    id: cost_range
    attributes:
      label: "Cost Range (NTD)"
      description: "Use '0' for free, or a range like '100-300' or '600+'"
      placeholder: "600+"
    validations:
      required: true

  - type: input
    id: age_range_min
    attributes:
      label: "Minimum Recommended Age"
      description: "Youngest appropriate age (0-18)"
      placeholder: "3"
    validations:
      required: true

  - type: input
    id: age_range_max
    attributes:
      label: "Maximum Recommended Age"
      description: "Oldest appropriate age (1-99)"
      placeholder: "12"
    validations:
      required: true

  # Features
  - type: checkboxes
    id: features
    attributes:
      label: "Features"
      description: "Select all that apply"
      options:
        - label: "Dog friendly"
        - label: "Food nearby"
        - label: "Seasonal"
        - label: "Natural attraction (not human-made)"

  # Location Information
  - type: input
    id: website
    attributes:
      label: "Official Website (optional)"
      description: "Full URL to the official website"
      placeholder: "https://example.com"
    validations:
      required: false

  - type: input
    id: map_link
    attributes:
      label: "Google Maps Link"
      description: "Full Google Maps URL to the exact location"
      placeholder: "https://maps.google.com/?q=..."
    validations:
      required: true

  - type: input
    id: address_en
    attributes:
      label: "Full Address (English)"
      description: "Complete address in English"
      placeholder: "No. 105, Chende Rd, Zhongli District, Taoyuan City, Taiwan 320"
    validations:
      required: true

  - type: input
    id: address_query
    attributes:
      label: "Map Search Query"
      description: "Search query that best finds this location on maps"
      placeholder: "Xpark Aquarium, Zhongli, Taoyuan, Taiwan"
    validations:
      required: true

  - type: input
    id: drive_min
    attributes:
      label: "Drive Time (minutes from Zhongli)"
      description: "Estimated driving time in minutes from Zhongli"
      placeholder: "25"
    validations:
      required: true

  # Additional Information
  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes (Optional)"
      description: "Any other important information (best times to visit, special requirements, etc.)"
      placeholder: "Best visited on weekdays to avoid crowds. Stroller accessible."
    validations:
      required: false
