name: Validate activities JSON
on: [pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm init -y && npm i ajv
      - name: Validate each record
        run: |
          node - <<'NODE'
          const fs=require('fs');const Ajv=require('ajv');
          const schema=JSON.parse(fs.readFileSync('data/activity.schema.json','utf8'));
          const data=JSON.parse(fs.readFileSync('data/activities_seed.json','utf8'));
          const ajv=new Ajv({allErrors:true});
          const val=ajv.compile(schema);
          for (const [i,rec] of data.entries()){
            const ok=val(rec);
            if(!ok){ console.error('Invalid at index', i, val.errors); process.exit(1); }
          }
          console.log('All good ✅');
          NODE
